{{- $virtualhost := index (pick .Orbit.Project.virtualhost .Orbit.EnvFile.ENV) .Orbit.EnvFile.ENV -}}
version: '3.3'


services:


  graylog-mongo:
    image: mongo:3.6.1-jessie
    container_name: {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }}-graylog-mongo
    restart: "no"
    networks:
      - backend
    labels:
      - traefik.enable=false
    volumes:
      - graylog_mongo_data:/data/db


  graylog-elasticsearch:
    image: elasticsearch:2.4.5-alpine
    container_name: {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }}-graylog-elasticsearch
    restart: "no"
    command: elasticsearch -Des.cluster.name='graylog'
    networks:
      - backend
    environment:
      - ES_JAVA_OPTS={{ .Orbit.EnvFile.GRAYLOG_ES_JAVA_OPTS }}
    labels:
      - traefik.enable=false
    volumes:
      - graylog_elasticsearch_data:/usr/share/elasticsearch/data


  graylog-server:
    image: graylog2/server:2.4.3-1
    container_name: {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }}-graylog
    restart: "no"
    networks:
      - proxy
      - backend
    ports:
      - "{{ .Orbit.EnvFile.GRAYLOG_PORT }}:{{ .Orbit.EnvFile.GRAYLOG_PORT }}/udp"
    environment:
      - GRAYLOG_ROOT_USERNAME={{ .Orbit.Modules.graylog.user }}
      {{- if eq "true" .Orbit.EnvFile.TRAEFIK_PREFIX }}
      - GRAYLOG_WEB_ENDPOINT_URI=https://graylog-{{ .Orbit.EnvFile.ENV }}.{{ $virtualhost }}/api/
      {{- else }}
      - GRAYLOG_WEB_ENDPOINT_URI=https://graylog.{{ $virtualhost }}/api/
      {{- end }}
      - GRAYLOG_MONGODB_URI=mongodb://graylog-mongo/graylog
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://graylog-elasticsearch:9200
      - GRAYLOG_CONTENT_PACKS_AUTO_LOAD=udp-input.json
      - GRAYLOG_CONTENT_PACKS_LOADER_ENABLED=true
      - GRAYLOG_CONTENT_PACKS_DIR=data/contentpacks
      - GRAYLOG_SERVER_JAVA_OPTS={{ .Orbit.EnvFile.GRAYLOG_SERVER_JAVA_OPTS }}
    env_file: ../toolbox/generated/graylog/.env
    labels:
      - traefik.backend={{ .Orbit.EnvFile.ENV }}-{{ .Orbit.Project.name }}-graylog
      {{- if eq "true" .Orbit.EnvFile.TRAEFIK_PREFIX }}
      - traefik.frontend.rule=Host:graylog-{{ .Orbit.EnvFile.ENV }}.{{ $virtualhost }}
      {{- else }}
      - traefik.frontend.rule=Host:graylog.{{ $virtualhost }}
      {{- end }}
      - traefik.port=9000
      - traefik.docker.network=kickoff_proxy
    volumes:
      - graylog_server_data:/usr/share/graylog/data/journal
      - ./udp-input.json:/usr/share/graylog/data/contentpacks/udp-input.json:ro


volumes:


  graylog_mongo_data:
    driver: local


  graylog_elasticsearch_data:
    driver: local


  graylog_server_data:
    driver: local


networks:


  proxy:
    external:
      name: kickoff_proxy


  backend:
    external:
      name: {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }}_backend