language: ruby

sudo: required

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.14.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - wget https://github.com/gulien/orbit/releases/download/v3.0.0/orbit_Linux_x86_64.tar.gz && tar -xzf orbit*.tar.gz orbit && rm -f orbit*.tar.gz
  - sudo mv ./orbit /usr/local/bin && chmod +x /usr/local/bin/orbit

script:
  - cp ./config/.env.blueprint ./config/.env
  # let's start a simple test without updating the configuration
  - orbit run kickoff shutdown
  # alright, now let's mimic a production environment
  - sed -i -e "s#ENV=local#ENV=test#g" ./config/.env
  - sed -i -e "s#TRAEFIK_CERT_FILE_PATH=#TRAEFIK_CERT_FILE_PATH=/home/travis/build/thecodingmachine/kickoff-docker-php/modules/toolbox/generated/traefik/certs/my-awesome-project.local.crt#g" ./config/.env
  - sed -i -e "s#TRAEFIK_KEY_FILE_PATH=#TRAEFIK_KEY_FILE_PATH=/home/travis/build/thecodingmachine/kickoff-docker-php/modules/toolbox/generated/traefik/certs/my-awesome-project.local.key#g" ./config/.env
  - orbit run kickoff shutdown
  # last but not least, let's disable optional modules
  - sed -i -e "s#true#false#g" ./config/modules.yml
  - orbit run kickoff shutdown

notifications:
  email: false