{{- $virtualhost := index (pick .Orbit.Project.virtualhost .Orbit.EnvFile.ENV) .Orbit.EnvFile.ENV -}}
version: '3.3'


services:


  toolbox:
    image: gulnap/kickoff-docker-php-images:toolbox-3.7-v2.4.0
    container_name: {{ .Orbit.EnvFile.ENV }}-{{ .Orbit.Project.name }}-toolbox
    networks:
      - backend
    environment:
      - VIRTUAL_HOST={{ $virtualhost }}
      - ENV={{ .Orbit.EnvFile.ENV }}
      - TRAEFIK_USER={{ .Orbit.Modules.traefik.user }}
      - TRAEFIK_PASSWORD={{ .Orbit.EnvFile.TRAEFIK_PASSWORD }}
      - GRAYLOG_ROOT_PASSWORD_SHA2={{ .Orbit.EnvFile.GRAYLOG_PASSWORD }}
      - GRAYLOG_ENABLED={{ .Orbit.Modules.graylog.enable }}
    labels:
      - traefik.enable=false
    volumes:
      - ./generated:/generated:rw
      - ./scripts:/scripts:ro


networks:


  backend:
    driver: bridge