{{- $virtualhost := index (pick .Orbit.Project.virtualhost .Orbit.EnvFile.ENV) .Orbit.EnvFile.ENV -}}
# Entry points definition
defaultEntryPoints = ["http", "https"]

[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"
[entryPoints.https]
address = ":443"
[entryPoints.https.tls]
[[entryPoints.https.tls.certificates]]
certFile = "certs/{{ $virtualhost }}.crt"
keyFile = "certs/{{ $virtualhost }}.key"

# API backend
[web]
address = ":8080"
{{- if ne "local" .Orbit.EnvFile.ENV }}
[web.auth.digest]
usersFile = "auth/.htdigest"
{{- end }}