# |--------------------------------------------------------------------------
# | Scripts tasks
# |--------------------------------------------------------------------------
# |
# | This file describes the scripts tasks of your project.
# | Feel free to add your own tasks!
# |
# | https://github.com/gulien/orbit/
# |

tasks:

  # |--------------------------------------------------------------------------
  # | orbit run script-fix-permissions-docker-sync
  # |--------------------------------------------------------------------------
  # |
  # | Fixes "www-data" permissions issues with Docker Sync.
  # |

  - use: script-fix-permissions-docker-sync
    run:
      {{ if and (ne "windows" os) (eq "true" .Orbit.EnvFile.ENABLE_DOCKER_SYNC) }}
      - config/scripts/fix-permissions.sh
      {{ else }}
      - echo Skipping UID binding for "www-data" with Docker Sync ...
      {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run script-fix-permissions-nginx
  # |--------------------------------------------------------------------------
  # |
  # | Fixes "www-data" permissions issues in the NGINX container.
  # |

  - use: script-fix-permissions-nginx
    run:
       {{ if ne "windows" os }}
       - config/scripts/fix-permissions.sh NGINX
       {{ else }}
       - echo Skipping UID binding for "www-data" user in the NGINX container ...
       {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run script-fix-permissions-php-fpm
  # |--------------------------------------------------------------------------
  # |
  # | Fixes "www-data" permissions issues in the PHP-FPM container.
  # |

  - use: script-fix-permissions-php-fpm
    run:
       {{ if ne "windows" os }}
       - config/scripts/fix-permissions.sh PHP-FPM
       {{ else }}
       - echo Skipping UID binding for "www-data" user in the PHP-FPM container ...
       {{ end }}

  # |--------------------------------------------------------------------------
  # | orbit run script-traefik-self-signed-certificate
  # |--------------------------------------------------------------------------
  # |
  # | Generates the self-signed certificate if current environment is "local".
  # |

  - use: script-traefik-self-signed-certificate
    run:
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/toolbox/docker-compose.yml run --rm toolbox /bin/sh -c /scripts/traefik-self-signed-certificate.sh

  # |--------------------------------------------------------------------------
  # | orbit run script-traefik-htdigest
  # |--------------------------------------------------------------------------
  # |
  # | Generates the .htdigest file which is used to authenticate on the Traefik
  # | dashboard.
  # |
  # | Only for environments <> "local".
  # |

  - use: script-traefik-htdigest
    run:
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/toolbox/docker-compose.yml run --rm toolbox /bin/sh -c  /scripts/traefik-htdigest.sh

  # |--------------------------------------------------------------------------
  # | orbit run script-graylog-secrets
  # |--------------------------------------------------------------------------
  # |
  # | Generates Graylog secrets.
  # |

  - use: script-graylog-secrets
    run:
      - docker-compose -p {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }} -f modules/toolbox/docker-compose.yml run --rm toolbox /bin/sh -c /scripts/graylog-secrets.sh