# |--------------------------------------------------------------------------
# | Tasks for commands
# |--------------------------------------------------------------------------
# |
# | This file describes the commands from the containers of your project.
# | Feel free to add your own tasks!
# |
# | https://github.com/gulien/orbit/
# |

tasks:

  # |--------------------------------------------------------------------------
  # | orbit run command-workspace
  # |--------------------------------------------------------------------------
  # |
  # | Connects through ash to the PHP-FPM container.
  # |

  - use: command-workspace
    run:
      - docker exec --user www-data -ti {{ .Orbit.EnvFile.ENV }}-{{ .Orbit.Project.name }}-php-fpm ash

  # |--------------------------------------------------------------------------
  # | orbit run command-mysql-cli
  # |--------------------------------------------------------------------------
  # |
  # | Opens the MySQL CLI as root.
  # |
  # | On environments <> "local", it will ask you the MySQL root password.
  # |

  - use: command-mysql-cli
    run:
      {{ if eq true .Orbit.Modules.mysql.enable }}
      - docker exec -ti {{ .Orbit.EnvFile.ENV }}-{{ .Orbit.Project.name }}-mysql mysql -uroot -p{{ if eq "local" .Orbit.EnvFile.ENV }}{{ .Orbit.EnvFile.MYSQL_ROOT_PASSWORD }}{{ end }}
      {{ else }}
      - echo MySQL is not enable!
      {{ end }}