version: '3.3'


services:


  redis:
    image: redis:3.2.11-alpine
    container_name: {{ .Orbit.EnvFile.ENV }}-{{ .Orbit.Project.name }}-redis
    restart: {{ if and (ne "local" .Orbit.EnvFile.ENV) (eq false .Orbit.Modules.graylog.enable) }}unless-stopped{{ else }}"no"{{ end }}
    command: redis-server --requirepass {{ .Orbit.EnvFile.REDIS_PASSWORD }}
    networks:
      - backend
    labels:
      - traefik.enable=false
    volumes:
      - redis_data:/data
    {{- if eq true .Orbit.Modules.graylog.enable }}
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:{{ .Orbit.EnvFile.GRAYLOG_PORT }}
    {{ end }}

networks:


  backend:
    external:
      name: {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }}_backend


volumes:


  redis_data:
    driver: local